spring.application.name=Info
spring.datasource.url=jdbc:mysql://localhost:3306/py_pro?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Yb1503447@@@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8998

# ? MyBatis ??
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.zxjz.info
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl